# permissions for end users to view postgrestables.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: postgrestable-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: postgres-dev-operator
    app.kubernetes.io/part-of: postgres-dev-operator
    app.kubernetes.io/managed-by: kustomize
  name: postgrestable-viewer-role
rules:
- apiGroups:
  - db.c-t-n
  resources:
  - postgrestables
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - db.c-t-n
  resources:
  - postgrestables/status
  verbs:
  - get
