---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - db.c-t-n
  resources:
  - postgresdatabases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - db.c-t-n
  resources:
  - postgresdatabases/finalizers
  verbs:
  - update
- apiGroups:
  - db.c-t-n
  resources:
  - postgresdatabases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - db.c-t-n
  resources:
  - postgrestables
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - db.c-t-n
  resources:
  - postgrestables/finalizers
  verbs:
  - update
- apiGroups:
  - db.c-t-n
  resources:
  - postgrestables/status
  verbs:
  - get
  - patch
  - update
